/**
 * Created by Daniel on 15/01/2017.
 */
export const MODALS = {
    NONE: 'NONE',
    NODE_MODAL: 'NODE_MODAL',
    DELETE_NODE_MODAL: 'DELETE_NODE_MODAL',
    SHARE_NODE_MODAL: 'SHARE_NODE_MODAL',
    LEAVE_NODE_MODAL: 'LEAVE_NODE_MODAL',
    WALK_THROUGH_MODAL: 'WALK_THROUGH_MODAL',
    INVITATION_MODAL: 'INVITATION_MODAL'
};